### ISSUE TITLE
A and B buttons are swapped

### ISSUE THREAD

**Issue by LatteStarbuck** [Clownacy/Sonic-Mania-Decompilation#5]
Why are they swapped? (Using gamepad here) B is accept and A is cancel.

**Comment by Clownacy** [comment]
It's an issue with the upstream decompilation: even when building for the Nintendo Switch, the A and B buttons are swapped. This Wii U port borrows a lot of code from the Switch port, so this bug was inherited.

I've fixed it in [this commit](https://github.com/Clownacy/RSDKv5-Decompilation/commit/6f16bd166ad06ad2869a89d954f88443e649b59f), so the buttons should be correct in the next release. Thanks for the report.
